//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seemplexity.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available places.
        /// </summary>
        public static string AvailablePlaces {
            get {
                return ResourceManager.GetString("AvailablePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balkan Express.
        /// </summary>
        public static string BalkanExpress {
            get {
                return ResourceManager.GetString("BalkanExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Sended.
        /// </summary>
        public static string BookingSended {
            get {
                return ResourceManager.GetString("BookingSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus descriptions.
        /// </summary>
        public static string BusDescriptions {
            get {
                return ResourceManager.GetString("BusDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buses.
        /// </summary>
        public static string Buses {
            get {
                return ResourceManager.GetString("Buses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus tickets.
        /// </summary>
        public static string BusTickets {
            get {
                return ResourceManager.GetString("BusTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus tours.
        /// </summary>
        public static string BusTours {
            get {
                return ResourceManager.GetString("BusTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string ClickToLogIn {
            get {
                return ResourceManager.GetString("ClickToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account confirmation.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking {0}.
        /// </summary>
        public static string ConfirmAccountMessageBody {
            get {
                return ResourceManager.GetString("ConfirmAccountMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation has been sended to your EMail.
        /// </summary>
        public static string ConfirmationHasSended {
            get {
                return ResourceManager.GetString("ConfirmationHasSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string ConfirmingEmail {
            get {
                return ResourceManager.GetString("ConfirmingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create bus description.
        /// </summary>
        public static string CreateBusDescription {
            get {
                return ResourceManager.GetString("CreateBusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create scheme.
        /// </summary>
        public static string CreateScheme {
            get {
                return ResourceManager.GetString("CreateScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curorts.
        /// </summary>
        public static string Curorts {
            get {
                return ResourceManager.GetString("Curorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure place.
        /// </summary>
        public static string DeparturePlace {
            get {
                return ResourceManager.GetString("DeparturePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time.
        /// </summary>
        public static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit scheme.
        /// </summary>
        public static string EditScheme {
            get {
                return ResourceManager.GetString("EditScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail сonfirmed.
        /// </summary>
        public static string EMailConfirmed {
            get {
                return ResourceManager.GetString("EMailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request. We are working on it..
        /// </summary>
        public static string ErrorRequest {
            get {
                return ResourceManager.GetString("ErrorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find buses.
        /// </summary>
        public static string FindBuses {
            get {
                return ResourceManager.GetString("FindBuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to pay.
        /// </summary>
        public static string HowToPay {
            get {
                return ResourceManager.GetString("HowToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HowToUse.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In bus.
        /// </summary>
        public static string InBus {
            get {
                return ResourceManager.GetString("InBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in price.
        /// </summary>
        public static string IncludeInPrice {
            get {
                return ResourceManager.GetString("IncludeInPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info not found.
        /// </summary>
        public static string InfoNotFound {
            get {
                return ResourceManager.GetString("InfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places.
        /// </summary>
        public static string NoPlaces {
            get {
                return ResourceManager.GetString("NoPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer is not done on resorts.
        /// </summary>
        public static string NotCarried {
            get {
                return ResourceManager.GetString("NotCarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your EMail doesn&apos;t confirmed.
        /// </summary>
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of places.
        /// </summary>
        public static string NumberOfPlaces {
            get {
                return ResourceManager.GetString("NumberOfPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of our addresses.
        /// </summary>
        public static string OurAdresses {
            get {
                return ResourceManager.GetString("OurAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner key.
        /// </summary>
        public static string PartnerKey {
            get {
                return ResourceManager.GetString("PartnerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PassDontMatch {
            get {
                return ResourceManager.GetString("PassDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long.
        /// </summary>
        public static string PassInvalid {
            get {
                return ResourceManager.GetString("PassInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport series.
        /// </summary>
        public static string PassportSeria {
            get {
                return ResourceManager.GetString("PassportSeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment methods.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash, right before the trip.
        /// </summary>
        public static string PaymentMethodsCach {
            get {
                return ResourceManager.GetString("PaymentMethodsCach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash in our office.
        /// </summary>
        public static string PaymentMethodsCachOffice {
            get {
                return ResourceManager.GetString("PaymentMethodsCachOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card by invoice number (you get it after selecting the place (s) and send the application form).
        /// </summary>
        public static string PaymentMethodsCredtCard {
            get {
                return ResourceManager.GetString("PaymentMethodsCredtCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With return ticket only.
        /// </summary>
        public static string RtOnly {
            get {
                return ResourceManager.GetString("RtOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule dates.
        /// </summary>
        public static string ScheduleDates {
            get {
                return ResourceManager.GetString("ScheduleDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        public static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme not found.
        /// </summary>
        public static string SchemeNotFound {
            get {
                return ResourceManager.GetString("SchemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service list key.
        /// </summary>
        public static string ServiceListKey {
            get {
                return ResourceManager.GetString("ServiceListKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for confirmation.
        /// </summary>
        public static string ThanksConfirmation {
            get {
                return ResourceManager.GetString("ThanksConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There.
        /// </summary>
        public static string There {
            get {
                return ResourceManager.GetString("There", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket from.
        /// </summary>
        public static string TicketFrom {
            get {
                return ResourceManager.GetString("TicketFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets reservation.
        /// </summary>
        public static string TicketsReservation {
            get {
                return ResourceManager.GetString("TicketsReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For ticket reservation is required to register.
        /// </summary>
        public static string TicketsReservationRegister {
            get {
                return ResourceManager.GetString("TicketsReservationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket to.
        /// </summary>
        public static string TicketTo {
            get {
                return ResourceManager.GetString("TicketTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to seat.
        /// </summary>
        public static string TimeToSeat {
            get {
                return ResourceManager.GetString("TimeToSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To main site.
        /// </summary>
        public static string ToMainSite {
            get {
                return ResourceManager.GetString("ToMainSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To partners.
        /// </summary>
        public static string ToPartners {
            get {
                return ResourceManager.GetString("ToPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour types.
        /// </summary>
        public static string TourTypes {
            get {
                return ResourceManager.GetString("TourTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport key.
        /// </summary>
        public static string TransportKey {
            get {
                return ResourceManager.GetString("TransportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload excursion file.
        /// </summary>
        public static string UploadExcursionFile {
            get {
                return ResourceManager.GetString("UploadExcursionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload tourists list file.
        /// </summary>
        public static string UploadTouristsListFile {
            get {
                return ResourceManager.GetString("UploadTouristsListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload transfer file.
        /// </summary>
        public static string UploadTransferFile {
            get {
                return ResourceManager.GetString("UploadTransferFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
    }
}
