//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddDescript2
    {
        public int A2_KEY { get; set; }
        public Nullable<int> A2_SVKEY { get; set; }
        public string A2_CODE { get; set; }
        public string A2_NAME { get; set; }
        public string A2_NAMELAT { get; set; }
        public byte[] ROWID { get; set; }
        public string A2_StdKey { get; set; }
        public string A2_Url { get; set; }
        public int A2_ShowOrder { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
