//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddDescript1
    {
        public int A1_KEY { get; set; }
        public Nullable<int> A1_SVKEY { get; set; }
        public string A1_CODE { get; set; }
        public string A1_NAME { get; set; }
        public string A1_NAMELAT { get; set; }
        public byte[] ROWID { get; set; }
        public string A1_StdKey { get; set; }
        public int A1_ShowOrder { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
