//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcurDictionary
    {
        public int ED_CNKEY { get; set; }
        public int ED_CTKEY { get; set; }
        public int ED_KEY { get; set; }
        public string ED_NAME { get; set; }
        public string ED_NAMELAT { get; set; }
        public Nullable<System.DateTime> ED_TIMEBEG { get; set; }
        public Nullable<System.DateTime> ED_TIMEEND { get; set; }
        public string ED_TIME { get; set; }
        public string ED_PLACEFROM { get; set; }
        public string ED_PLACETO { get; set; }
        public string ED_REMARK { get; set; }
        public string ED_COMMENT { get; set; }
        public byte[] ROWID { get; set; }
        public string ED_StdKey { get; set; }
        public string ED_Url { get; set; }
        public int ED_ShowOrder { get; set; }
    }
}
