//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDictionary
    {
        public int HD_CNKEY { get; set; }
        public int HD_CTKEY { get; set; }
        public int HD_KEY { get; set; }
        public string HD_NAME { get; set; }
        public string HD_STARS { get; set; }
        public string HD_ADDRESS { get; set; }
        public string HD_PHONE { get; set; }
        public string HD_FAX { get; set; }
        public Nullable<short> HD_SITE { get; set; }
        public string HD_DESCRIPT { get; set; }
        public string HD_PERSONNAME { get; set; }
        public string HD_PERSONAPP { get; set; }
        public string HD_CODE { get; set; }
        public Nullable<int> HD_RSKEY { get; set; }
        public string HD_EMAIL { get; set; }
        public string HD_HTTP { get; set; }
        public string HD_DESCROOM { get; set; }
        public string HD_DESCMEAL { get; set; }
        public string HD_DESCSERVICE { get; set; }
        public string HD_DESCSPORT { get; set; }
        public string HD_DESCEXCUR { get; set; }
        public string HD_DESCHEALTH { get; set; }
        public Nullable<double> HD_DISTANCE { get; set; }
        public Nullable<int> HD_WEB { get; set; }
        public string HD_DESCRAZVL { get; set; }
        public string HD_WEBIMAGE { get; set; }
        public string HD_WEBIMAGE1 { get; set; }
        public string HD_WEBIMAGE2 { get; set; }
        public string HD_WEBIMAGE3 { get; set; }
        public string HD_WEBIMAGE4 { get; set; }
        public string HD_WEBIMAGE5 { get; set; }
        public string HD_WEBIMAGE6 { get; set; }
        public string HD_WEBIMAGE7 { get; set; }
        public string HD_WEBIMAGE8 { get; set; }
        public string HD_REMARK { get; set; }
        public string HD_REMARK1 { get; set; }
        public string HD_REMARK2 { get; set; }
        public string HD_REMARK3 { get; set; }
        public string HD_REMARK4 { get; set; }
        public string HD_REMARK5 { get; set; }
        public string HD_REMARK6 { get; set; }
        public string HD_REMARK7 { get; set; }
        public string HD_REMARK8 { get; set; }
        public byte[] ROWID { get; set; }
        public string HD_StdKey { get; set; }
        public string HD_UNICODE { get; set; }
        public System.DateTime HD_UPDATEDATE { get; set; }
        public Nullable<int> HD_Order { get; set; }
        public int HD_IsCruise { get; set; }
        public Nullable<int> HD_COHId { get; set; }
        public string HD_NAMELAT { get; set; }
        public Nullable<System.DateTime> HD_PayHour1 { get; set; }
        public Nullable<System.DateTime> HD_PayHour2 { get; set; }
        public string HD_Travel { get; set; }
        public string HD_PayHourNote { get; set; }
        public Nullable<int> hd_rank { get; set; }
        public string HD_HTTPAdditional { get; set; }
    }
}
