//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TurList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TurList()
        {
            this.TurDates = new HashSet<TurDate>();
            this.TurServices = new HashSet<TurService>();
        }
    
        public int TL_CNKEY { get; set; }
        public int TL_KEY { get; set; }
        public string TL_NAME { get; set; }
        public Nullable<short> TL_TYPECOUNT { get; set; }
        public Nullable<double> TL_PROFIT { get; set; }
        public Nullable<double> TL_PRICE { get; set; }
        public short TL_NDAY { get; set; }
        public Nullable<int> TL_CREATOR { get; set; }
        public string TL_DESCRIPTION { get; set; }
        public string TL_REMARK { get; set; }
        public string TL_RATE { get; set; }
        public string TL_WEBHTTP { get; set; }
        public string TL_NAMEWEB { get; set; }
        public Nullable<int> TL_WEB { get; set; }
        public Nullable<int> TL_DATEDOC { get; set; }
        public Nullable<int> TL_DATEDOCVISA { get; set; }
        public int TL_TIP { get; set; }
        public string TL_WEBCOST { get; set; }
        public byte[] ROWID { get; set; }
        public string TL_EMAIL { get; set; }
        public Nullable<int> TL_datequotes { get; set; }
        public Nullable<int> TL_datepayed { get; set; }
        public Nullable<double> TL_DfltPaymentPcnt { get; set; }
        public Nullable<decimal> TL_Margin { get; set; }
        public Nullable<short> TL_MarginType { get; set; }
        public Nullable<int> TL_PRKey { get; set; }
        public Nullable<int> TL_OpKey { get; set; }
        public short TL_IsDisabled { get; set; }
        public Nullable<int> TL_RGKEY { get; set; }
        public string TL_ADVDESC { get; set; }
        public string TL_ATTDESC { get; set; }
        public string TL_DOPDESC { get; set; }
        public string TL_FULLDESC { get; set; }
        public string TL_SMALLDESC { get; set; }
        public short TL_Deleted { get; set; }
        public Nullable<int> TL_LEADDEPARTMENT { get; set; }
        public string TL_NameLat { get; set; }
        public Nullable<int> TL_CTDepartureKey { get; set; }
        public string tl_webHttpPers { get; set; }
        public int TL_Attribute { get; set; }
        public int TL_CalculationAction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurDate> TurDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurService> TurServices { get; set; }
        public virtual TipTur TipTur { get; set; }
    }
}
