//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Costs
    {
        public int CS_SVKEY { get; set; }
        public int CS_CODE { get; set; }
        public Nullable<int> CS_SUBCODE1 { get; set; }
        public Nullable<int> CS_SUBCODE2 { get; set; }
        public int CS_PRKEY { get; set; }
        public Nullable<int> CS_PKKEY { get; set; }
        public Nullable<System.DateTime> CS_DATE { get; set; }
        public Nullable<System.DateTime> CS_DATEEND { get; set; }
        public string CS_WEEK { get; set; }
        public double CS_COSTNETTO { get; set; }
        public double CS_COST { get; set; }
        public Nullable<short> CS_DISCOUNT { get; set; }
        public Nullable<short> CS_TYPE { get; set; }
        public int CS_CREATOR { get; set; }
        public string CS_RATE { get; set; }
        public Nullable<System.DateTime> CS_UPDDATE { get; set; }
        public Nullable<short> CS_LONG { get; set; }
        public short CS_BYDAY { get; set; }
        public Nullable<short> CS_FIRSTDAYNETTO { get; set; }
        public Nullable<short> CS_FIRSTDAYBRUTTO { get; set; }
        public Nullable<double> CS_PROFIT { get; set; }
        public byte[] ROWID { get; set; }
        public Nullable<int> CS_CINNUM { get; set; }
        public Nullable<short> CS_TypeCalc { get; set; }
        public Nullable<System.DateTime> cs_DateSellBeg { get; set; }
        public Nullable<System.DateTime> cs_DateSellEnd { get; set; }
        public int CS_ID { get; set; }
        public Nullable<System.DateTime> CS_CHECKINDATEBEG { get; set; }
        public Nullable<System.DateTime> CS_CHECKINDATEEND { get; set; }
        public Nullable<short> CS_LONGMIN { get; set; }
        public Nullable<short> CS_TypeDivision { get; set; }
        public string CS_UPDUSER { get; set; }
        public int CS_TRFId { get; set; }
        public Nullable<int> CS_COID { get; set; }
    }
}
