//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Turist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Turist()
        {
            this.TuristServices = new HashSet<TuristService>();
        }
    
        public string TU_DGCOD { get; set; }
        public int TU_KEY { get; set; }
        public Nullable<System.DateTime> TU_TURDATE { get; set; }
        public string TU_NAMERUS { get; set; }
        public string TU_NAMELAT { get; set; }
        public string TU_SHORTNAME { get; set; }
        public Nullable<short> TU_SEX { get; set; }
        public string TU_FNAMERUS { get; set; }
        public string TU_FNAMELAT { get; set; }
        public string TU_SNAMERUS { get; set; }
        public string TU_SNAMELAT { get; set; }
        public Nullable<System.DateTime> TU_BIRTHDAY { get; set; }
        public string TU_BIRTHCOUNTRY { get; set; }
        public string TU_BIRTHCITY { get; set; }
        public string TU_CITIZEN { get; set; }
        public string TU_POSTINDEX { get; set; }
        public string TU_POSTCITY { get; set; }
        public string TU_POSTSTREET { get; set; }
        public string TU_POSTBILD { get; set; }
        public string TU_POSTFLAT { get; set; }
        public string TU_PHONE { get; set; }
        public string TU_PHONECODE { get; set; }
        public string TU_PASPORTTYPE { get; set; }
        public string TU_PASPORTNUM { get; set; }
        public Nullable<System.DateTime> TU_PASPORTDATE { get; set; }
        public Nullable<System.DateTime> TU_PASPORTDATEEND { get; set; }
        public string TU_PASPORTBYWHOM { get; set; }
        public Nullable<short> TU_PLACE { get; set; }
        public Nullable<short> TU_ISANKETA { get; set; }
        public int TU_CREATOR { get; set; }
        public int TU_OWNER { get; set; }
        public string TU_PASPRUSER { get; set; }
        public string TU_PASPRUNUM { get; set; }
        public Nullable<System.DateTime> TU_PASPRUDATE { get; set; }
        public string TU_PASPRUBYWHOM { get; set; }
        public string TU_INSURPOLIS { get; set; }
        public Nullable<double> TU_INSURSUM { get; set; }
        public Nullable<double> TU_DISCOUNT { get; set; }
        public Nullable<double> TU_TYPEDISCOUNT { get; set; }
        public Nullable<int> TU_ID { get; set; }
        public Nullable<short> TU_ISMAIN { get; set; }
        public byte[] ROWID { get; set; }
        public Nullable<int> TU_AgentID { get; set; }
        public Nullable<int> TU_DGKEY { get; set; }
        public Nullable<short> TU_RealSex { get; set; }
        public string TU_EMAIL { get; set; }
        public short TU_EnableSmsNotifications { get; set; }
        public bool TU_InsuredEvent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuristService> TuristServices { get; set; }
    }
}
