//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Country()
        {
            this.ServiceLists = new HashSet<ServiceList>();
        }
    
        public int CN_KEY { get; set; }
        public string CN_NAME { get; set; }
        public string CN_NAMELAT { get; set; }
        public Nullable<int> CN_FRAME { get; set; }
        public Nullable<int> CN_WEB { get; set; }
        public string CN_WEBIMAGE { get; set; }
        public string CN_WEBHTTP { get; set; }
        public string CN_CODE { get; set; }
        public byte[] ROWID { get; set; }
        public short CN_AnkLang { get; set; }
        public string CN_StdKey { get; set; }
        public Nullable<System.DateTime> CN_Updatedate { get; set; }
        public string CN_SMALLDESC { get; set; }
        public Nullable<int> CN_COKey { get; set; }
        public string CN_NameAC { get; set; }
        public Nullable<int> CN_Order { get; set; }
        public string CN_CitizenName { get; set; }
        public string CN_CitizenNameLat { get; set; }
        public string CN_INNName { get; set; }
        public bool CN_CheckINN { get; set; }
        public Nullable<int> CN_PassportMinDur { get; set; }
        public Nullable<int> CN_RateKey { get; set; }
        public int CN_PassportMinDurCheckFrom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceList> ServiceLists { get; set; }
    }
}
