//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipTur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipTur()
        {
            this.tbl_TurList = new HashSet<tbl_TurList>();
            this.TipTur1 = new HashSet<TipTur>();
        }
    
        public int TP_KEY { get; set; }
        public string TP_NAME { get; set; }
        public Nullable<int> TP_TPKEY { get; set; }
        public string TP_NameLat { get; set; }
        public Nullable<int> TP_Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TurList> tbl_TurList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipTur> TipTur1 { get; set; }
        public virtual TipTur TipTur2 { get; set; }
    }
}
