//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurDate
    {
        public int TD_TRKEY { get; set; }
        public System.DateTime TD_DATE { get; set; }
        public int TD_Id { get; set; }
    
        public virtual tbl_TurList tbl_TurList { get; set; }
    }
}
