//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuristService
    {
        public int TU_TUKEY { get; set; }
        public int TU_DLKEY { get; set; }
        public string TU_NUMDOC { get; set; }
        public Nullable<short> TU_NUMROOM { get; set; }
        public string TU_SEAT { get; set; }
        public Nullable<short> TU_AREA { get; set; }
        public Nullable<System.DateTime> TU_DOCDATE { get; set; }
        public byte[] ROWID { get; set; }
        public int TU_IDKEY { get; set; }
    
        public virtual tbl_Turist tbl_Turist { get; set; }
    }
}
