//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurService
    {
        public int TS_TRKEY { get; set; }
        public int TS_SVKEY { get; set; }
        public Nullable<int> TS_PKKEY { get; set; }
        public string TS_NAME { get; set; }
        public Nullable<short> TS_DAY { get; set; }
        public int TS_CODE { get; set; }
        public Nullable<int> TS_SUBCODE1 { get; set; }
        public Nullable<int> TS_SUBCODE2 { get; set; }
        public Nullable<short> TS_NDAYS { get; set; }
        public int TS_CNKEY { get; set; }
        public Nullable<int> TS_CTKEY { get; set; }
        public Nullable<int> TS_PARTNERKEY { get; set; }
        public Nullable<double> TS_COST { get; set; }
        public Nullable<double> TS_PROFIT { get; set; }
        public Nullable<System.DateTime> TS_TIMEBEG { get; set; }
        public Nullable<int> TS_ATTRIBUTE { get; set; }
        public byte[] ROWID { get; set; }
        public int TS_Key { get; set; }
        public string TS_NameLat { get; set; }
        public Nullable<int> TS_PRTDOGKEY { get; set; }
        public Nullable<int> TS_TAXZONEID { get; set; }
        public Nullable<int> TS_WebAttribute { get; set; }
        public Nullable<short> TS_Wait { get; set; }
        public int TS_TRFId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual tbl_TurList tbl_TurList { get; set; }
    }
}
