//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seemplexity.Avalon.BusinesLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclePlan
    {
        public int VP_VHKEY { get; set; }
        public int VP_VHROW { get; set; }
        public int VP_VHAREANUMBER { get; set; }
        public string VP_SEATNUMBER1 { get; set; }
        public string VP_SEATNUMBER2 { get; set; }
        public string VP_SEATNUMBER3 { get; set; }
        public string VP_SEATNUMBER4 { get; set; }
        public string VP_SEATNUMBER5 { get; set; }
        public string VP_SEATNUMBER6 { get; set; }
        public string VP_SEATNUMBER7 { get; set; }
        public string VP_SEATNUMBER8 { get; set; }
        public string VP_SEATNUMBER9 { get; set; }
        public string VP_SEATNUMBER10 { get; set; }
        public string VP_SEATNUMBER11 { get; set; }
        public string VP_SEATNUMBER12 { get; set; }
        public Nullable<short> VP_SEATTYPE1 { get; set; }
        public Nullable<short> VP_SEATTYPE2 { get; set; }
        public Nullable<short> VP_SEATTYPE3 { get; set; }
        public Nullable<short> VP_SEATTYPE4 { get; set; }
        public Nullable<short> VP_SEATTYPE5 { get; set; }
        public Nullable<short> VP_SEATTYPE6 { get; set; }
        public Nullable<short> VP_SEATTYPE7 { get; set; }
        public Nullable<short> VP_SEATTYPE8 { get; set; }
        public Nullable<short> VP_SEATTYPE9 { get; set; }
        public Nullable<short> VP_SEATTYPE10 { get; set; }
        public Nullable<short> VP_SEATTYPE11 { get; set; }
        public Nullable<short> VP_SEATTYPE12 { get; set; }
        public Nullable<short> VP_SEATMEN1 { get; set; }
        public Nullable<short> VP_SEATMEN2 { get; set; }
        public Nullable<short> VP_SEATMEN3 { get; set; }
        public Nullable<short> VP_SEATMEN4 { get; set; }
        public Nullable<short> VP_SEATMEN5 { get; set; }
        public Nullable<short> VP_SEATMEN6 { get; set; }
        public Nullable<short> VP_SEATMEN7 { get; set; }
        public Nullable<short> VP_SEATMEN8 { get; set; }
        public Nullable<short> VP_SEATMEN9 { get; set; }
        public Nullable<short> VP_SEATMEN10 { get; set; }
        public Nullable<short> VP_SEATMEN11 { get; set; }
        public Nullable<short> VP_SEATMEN12 { get; set; }
        public byte[] ROWID { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
